# Generated by Django 3.1 on 2020-09-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('primary', 'Primary'), ('junior', 'Junior'), ('secondary', 'Secondary')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('other_names', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_ledger.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_ledger.bank')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_ledger.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='class_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_ledger.studentclass'),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_ledger.academicsession'),
        ),
        migrations.AddField(
            model_name='bill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_ledger.student'),
        ),
        migrations.AddField(
            model_name='bill',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_ledger.academicterm'),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_bank'),
        ),
    ]
