# Generated by Django 3.1 on 2020-09-26 12:13

from django.db import migrations
from django.contrib.auth.hashers import make_password


def default_site_config(apps, schema_editor):
    """ Default site configurations """

    User = apps.get_model('users', 'User')
    a = User.objects.create(email='admin@admin.com', is_superuser=True, password=make_password('admin'))

    Session = apps.get_model('student_ledger', 'AcademicSession')
    Session.objects.bulk_create([
        Session(name='2019/2020', current=True),
        Session(name='2020/2021', current=False),
    ])

    Term = apps.get_model('student_ledger', 'AcademicTerm')
    Term.objects.bulk_create([
        Term(name='1st Term', current=True),
        Term(name='2nd Term', current=False),
        Term(name='3rd Term', current=False),
    ])

    StudentClass = apps.get_model('student_ledger', 'StudentClass')
    StudentClass.objects.bulk_create([
        StudentClass(name='JSS 1', category='junior'),
        StudentClass(name='JSS 2', category='junior'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('student_ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_site_config),
    ]
